export const TOURIST_LOCATIONS = [
    // Generic Cities & Countries
    "Paris, France", "London, United Kingdom", "New York, USA", "Rome, Italy", 
    "Tokyo, Japan", "Istanbul, Türkiye", "Dubai, UAE", "Singapore, Singapore",
    "Barcelona, Spain", "Amsterdam, Netherlands", "Madrid, Spain", "Prague, Czech Republic",
    "Bangkok, Thailand", "Seoul, South Korea", "Vienna, Austria", "Berlin, Germany",
    "Venice, Italy", "Milan, Italy", "Florence, Italy", "Athens, Greece", 
    "Santorini, Greece", "Mykonos, Greece", "Kyoto, Japan", "Osaka, Japan",
    "Los Angeles, USA", "San Francisco, USA", "Las Vegas, USA", "Miami, USA",
    "Toronto, Canada", "Vancouver, Canada", "Sydney, Australia", "Melbourne, Australia",
    "Rio de Janeiro, Brazil", "Buenos Aires, Argentina", "Cape Town, South Africa",
    "Cairo, Egypt", "Marrakech, Morocco", "Bali, Indonesia", "Phuket, Thailand",
    "Hanoi, Vietnam", "Ho Chi Minh City, Vietnam", "Kuala Lumpur, Malaysia",
    "Beijing, China", "Shanghai, China", "Hong Kong, China", "Taipei, Taiwan",
    "Munich, Germany", "Frankfurt, Germany", "Hamburg, Germany", "Zurich, Switzerland",
    "Geneva, Switzerland", "Lucerne, Switzerland", "Stockholm, Sweden", "Copenhagen, Denmark",
    "Oslo, Norway", "Helsinki, Finland", "Budapest, Hungary", "Warsaw, Poland",
    "Krakow, Poland", "Lisbon, Portugal", "Porto, Portugal", "Dublin, Ireland",
    "Edinburgh, United Kingdom", "Reykjavik, Iceland", "Dubrovnik, Croatia",
    "Split, Croatia", "Bratislava, Slovakia", "Ljubljana, Slovenia",
    "Antalya, Türkiye", "Izmir, Türkiye", "Cappadocia, Türkiye", "Bodrum, Türkiye",
    "Fethiye, Türkiye", "Marmaris, Türkiye", "Ankara, Türkiye", "Bursa, Türkiye",


    "Colosseum, Rome, Italy", "Eiffel Tower, Paris, France", "Statue of Liberty, New York, USA",
    "Great Wall, Beijing, China", "Taj Mahal, Agra, India", "Machu Picchu, Cusco, Peru",
    "Christ the Redeemer, Rio de Janeiro, Brazil", "Petra, Petra, Jordan", "Angkor Wat, Siem Reap, Cambodia",
    "Pyramids of Giza, Giza, Egypt", "Big Ben, London, United Kingdom", "Buckingham Palace, London, United Kingdom",
    "Louvre Museum, Paris, France", "Notre Dame Cathedral, Paris, France", "Sagrada Familia, Barcelona, Spain",
    "Park Güell, Barcelona, Spain", "Alhambra, Granada, Spain", "Acropolis, Athens, Greece",
    "Parthenon, Athens, Greece", "Santorini Caldera, Santorini, Greece", "Mount Fuji, Honshu, Japan",
    "Fushimi Inari Shrine, Kyoto, Japan", "Kinkaku-ji, Kyoto, Japan", "Tokyo Tower, Tokyo, Japan",
    "Shibuya Crossing, Tokyo, Japan", "Burj Khalifa, Dubai, UAE", "Palm Jumeirah, Dubai, UAE",
    "Sheikh Zayed Grand Mosque, Abu Dhabi, UAE", "Blue Mosque, Istanbul, Türkiye", "Hagia Sophia, Istanbul, Türkiye",
    "Cappadocia Fairy Chimneys, Nevşehir, Türkiye", "Pamukkale Travertines, Denizli, Türkiye", "Mount Nemrut, Adıyaman, Türkiye",
    "Stonehenge, Wiltshire, United Kingdom", "Tower Bridge, London, United Kingdom", "British Museum, London, United Kingdom",
    "Edinburgh Castle, Edinburgh, United Kingdom", "Neuschwanstein Castle, Bavaria, Germany", "Brandenburg Gate, Berlin, Germany",
    "Cologne Cathedral, Cologne, Germany", "Prague Castle, Prague, Czech Republic", "Charles Bridge, Prague, Czech Republic",
    "Schönbrunn Palace, Vienna, Austria", "Hallstatt Village, Hallstatt, Austria", "Leaning Tower of Pisa, Pisa, Italy",
    "St Peter’s Basilica, Vatican City, Vatican City", "Trevi Fountain, Rome, Italy", "Pantheon, Rome, Italy",
    "Pompeii Ruins, Pompeii, Italy", "Cinque Terre, Liguria, Italy", "Milan Cathedral, Milan, Italy",
    "Venice Grand Canal, Venice, Italy", "Doge’s Palace, Venice, Italy", "Mont Saint-Michel, Normandy, France",
    "Palace of Versailles, Versailles, France", "Arc de Triomphe, Paris, France", "Sacré-Cœur, Paris, France",
    "Disneyland Park, Anaheim, USA", "Golden Gate Bridge, San Francisco, USA", "Alcatraz Island, San Francisco, USA",
    "Grand Canyon, Arizona, USA", "Yellowstone National Park, Wyoming, USA", "Times Square, New York, USA",
    "Central Park, New York, USA", "Empire State Building, New York, USA", "Hollywood Sign, Los Angeles, USA",
    "Griffith Observatory, Los Angeles, USA", "Las Vegas Strip, Las Vegas, USA", "Niagara Falls, Ontario, Canada",
    "CN Tower, Toronto, Canada", "Banff National Park, Alberta, Canada", "Chichen Itza, Yucatán, Mexico",
    "Teotihuacan, Mexico City, Mexico", "Tulum Ruins, Tulum, Mexico", "Iguazu Falls, Iguazu, Argentina",
    "Perito Moreno Glacier, Patagonia, Argentina", "Sugarloaf Mountain, Rio de Janeiro, Brazil", "Amazon Rainforest, Amazonas, Brazil",
    "Easter Island Moai, Easter Island, Chile", "Salar de Uyuni, Uyuni, Bolivia", "Table Mountain, Cape Town, South Africa",
    "Kruger National Park, Mpumalanga, South Africa", "Victoria Falls, Livingstone, Zambia", "Serengeti National Park, Serengeti, Tanzania",
    "Mount Kilimanjaro, Kilimanjaro, Tanzania", "Pyramids of Meroe, Meroe, Sudan", "Luxor Temple, Luxor, Egypt",
    "Valley of the Kings, Luxor, Egypt", "Abu Simbel Temples, Abu Simbel, Egypt", "Wadi Rum Desert, Wadi Rum, Jordan",
    "Dead Sea, Dead Sea, Jordan", "Western Wall, Jerusalem, Israel", "Dome of the Rock, Jerusalem, Israel",
    "Masada Fortress, Masada, Israel", "Persepolis, Shiraz, Iran", "Nasir al-Mulk Mosque, Shiraz, Iran",
    "Sheikh Lotfollah Mosque, Isfahan, Iran", "Bagan Temples, Bagan, Myanmar", "Shwedagon Pagoda, Yangon, Myanmar",
    "Ha Long Bay, Quang Ninh, Vietnam", "Angkor Thom, Siem Reap, Cambodia", "Borobudur Temple, Magelang, Indonesia",
    "Prambanan Temple, Yogyakarta, Indonesia", "Komodo Island, Komodo, Indonesia", "Petronas Towers, Kuala Lumpur, Malaysia",
    "Batu Caves, Selangor, Malaysia", "Marina Bay Sands, Singapore, Singapore", "Gardens by the Bay, Singapore, Singapore",
    "Great Buddha, Hong Kong, China", "Victoria Peak, Hong Kong, China", "Forbidden City, Beijing, China",
    "Summer Palace, Beijing, China", "Terracotta Army, Xi’an, China", "Zhangjiajie National Park, Zhangjiajie, China",
    "Potala Palace, Lhasa, Tibet", "Jokhang Temple, Lhasa, Tibet", "N Seoul Tower, Seoul, South Korea",
    "Gyeongbokgung Palace, Seoul, South Korea", "Jeju Island, Jeju, South Korea", "Taipei 101, Taipei, Taiwan",
    "Sun Moon Lake, Nantou, Taiwan", "Sigiriya Rock Fortress, Sigiriya, Sri Lanka", "Temple of the Tooth, Kandy, Sri Lanka",
    "Everest Base Camp, Khumbu, Nepal", "Annapurna Circuit, Annapurna, Nepal", "Tiger’s Nest Monastery, Paro, Bhutan",
    "Thimphu Buddha Dordenma, Thimphu, Bhutan", "Red Fort, Delhi, India", "Hawa Mahal, Jaipur, India",
    "Golden Temple, Amritsar, India", "Qutub Minar, Delhi, India", "Mehrangarh Fort, Jodhpur, India",
    "Phi Phi Islands, Krabi, Thailand", "Grand Palace, Bangkok, Thailand", "Wat Arun, Bangkok, Thailand",
    "Wat Phra Kaew, Bangkok, Thailand", "Ayutthaya Ruins, Ayutthaya, Thailand", "Uluru, Northern Territory, Australia",
    "Sydney Opera House, Sydney, Australia", "Sydney Harbour Bridge, Sydney, Australia", "Great Barrier Reef, Queensland, Australia",
    "Blue Mountains, New South Wales, Australia", "Hobbiton Movie Set, Matamata, New Zealand", "Milford Sound, Fiordland, New Zealand",
    "Sky Tower, Auckland, New Zealand", "Te Papa Museum, Wellington, New Zealand", "Cliffs of Moher, Clare, Ireland",
    "Blarney Castle, Cork, Ireland", "Giant’s Causeway, Antrim, United Kingdom", "Skellig Michael, Kerry, Ireland",
    "Meteora Monasteries, Kalambaka, Greece", "Delphi Ruins, Delphi, Greece", "Mykonos Windmills, Mykonos, Greece",
    "Dubrovnik Old Town, Dubrovnik, Croatia", "Plitvice Lakes, Plitvice, Croatia", "Lake Bled, Bled, Slovenia",
    "Predjama Castle, Postojna, Slovenia", "Bran Castle, Brasov, Romania", "Palace of Parliament, Bucharest, Romania",
    "Buda Castle, Budapest, Hungary", "Fisherman’s Bastion, Budapest, Hungary", "Auschwitz Memorial, Oswiecim, Poland",
    "Wieliczka Salt Mine, Krakow, Poland", "Wawel Castle, Krakow, Poland", "Vilnius Old Town, Vilnius, Lithuania",
    "Riga Old Town, Riga, Latvia", "Tallinn Old Town, Tallinn, Estonia", "Helsinki Cathedral, Helsinki, Finland",
    "Suomenlinna Fortress, Helsinki, Finland", "Tivoli Gardens, Copenhagen, Denmark", "Nyhavn Harbor, Copenhagen, Denmark",
    "Oslo Opera House, Oslo, Norway", "Geirangerfjord, Geiranger, Norway", "Preikestolen, Rogaland, Norway",
    "Icehotel, Jukkasjärvi, Sweden", "Vasa Museum, Stockholm, Sweden", "Gamla Stan, Stockholm, Sweden",
    "Blue Lagoon, Grindavik, Iceland", "Gullfoss Waterfall, Iceland", "Thingvellir National Park, Iceland",
    "Chamonix Mont Blanc, Chamonix, France", "Mont Blanc, Alps, France", "Matterhorn, Zermatt, Switzerland",
    "Jungfraujoch, Jungfrau Region, Switzerland", "Château de Chillon, Montreux, Switzerland", "Andorra la Vella Old Town, Andorra la Vella, Andorra",
    "Monaco Harbor, Monaco, Monaco", "Monte Carlo Casino, Monte Carlo, Monaco", "Carthage Ruins, Tunis, Tunisia",
    "Medina of Marrakech, Marrakech, Morocco", "Hassan II Mosque, Casablanca, Morocco", "Ait Benhaddou, Ouarzazate, Morocco",
    "Lalibela Churches, Lalibela, Ethiopia", "Simien Mountains, Amhara, Ethiopia", "Robben Island, Cape Town, South Africa",
    "Okavango Delta, Botswana, Botswana", "Skeleton Coast, Namibia, Namibia", "Petra Treasury, Petra, Jordan",
    "Dead Sea Scrolls Cave, Qumran, West Bank", "Mount Sinai, Sinai Peninsula, Egypt", "Roman Forum, Rome, Italy",
    "Vatican Museums, Vatican City, Vatican City", "Sistine Chapel, Vatican City, Vatican City", "Florence Cathedral, Florence, Italy",
    "Uffizi Gallery, Florence, Italy", "Ponte Vecchio, Florence, Italy", "Grand Canal, Venice, Italy",
    "St Mark’s Basilica, Venice, Italy", "Rialto Bridge, Venice, Italy", "Amalfi Coast, Amalfi, Italy",
    "Capri Island, Capri, Italy", "Mount Etna, Sicily, Italy", "Sacré-Cœur Basilica, Paris, France",
    "Dune of Pilat, Arcachon, France", "Strasbourg Cathedral, Strasbourg, France", "Carcassonne Citadel, Carcassonne, France",
    "Pont du Gard, Nîmes, France", "Chartres Cathedral, Chartres, France", "La Rambla, Barcelona, Spain",
    "Plaza Mayor, Madrid, Spain", "Prado Museum, Madrid, Spain", "Royal Palace of Madrid, Madrid, Spain",
    "Seville Cathedral, Seville, Spain", "Plaza de España, Seville, Spain", "Guggenheim Museum, Bilbao, Spain",
    "Santiago de Compostela Cathedral, Santiago, Spain", "Belém Tower, Lisbon, Portugal", "Jerónimos Monastery, Lisbon, Portugal",
    "Pena Palace, Sintra, Portugal", "Quinta da Regaleira, Sintra, Portugal", "Ribeira District, Porto, Portugal",
    "London Eye, London, United Kingdom", "Westminster Abbey, London, United Kingdom", "Lake District National Park, Cumbria, United Kingdom",
    "Tower of London, London, United Kingdom", "St Paul’s Cathedral, London, United Kingdom", "Miniatur Wunderland, Hamburg, Germany",
    "Heidelberg Castle, Heidelberg, Germany", "Sanssouci Palace, Potsdam, Germany", "Marienplatz, Munich, Germany",
    "Belvedere Palace, Vienna, Austria", "Salzburg Old Town, Salzburg, Austria", "Hohensalzburg Fortress, Salzburg, Austria",
    "Old Town Square, Prague, Czech Republic", "Astronomical Clock, Prague, Czech Republic", "Hungarian Parliament Building, Budapest, Hungary",
    "Chain Bridge, Budapest, Hungary", "Postojna Cave, Postojna, Slovenia", "Plitvice Lakes National Park, Plitvice, Croatia",
    "Diocletian’s Palace, Split, Croatia", "Peles Castle, Sinaia, Romania", "Malbork Castle, Malbork, Poland",
    "Kronborg Castle, Helsingør, Denmark", "Lofoten Islands, Lofoten, Norway", "Drottningholm Palace, Stockholm, Sweden",
    "Skogafoss Waterfall, Iceland", "Seljalandsfoss Waterfall, Iceland", "Lake Geneva, Geneva, Switzerland",
    "Meteora Viewpoints, Kalambaka, Greece", "Mount Olympus, Thessaly, Greece", "Lake Como, Como, Italy",
    "Dolomites Mountains, Dolomites, Italy", "Zermatt Village, Zermatt, Switzerland", "Aletsch Glacier, Valais, Switzerland",
    "Sognefjord, Sogn og Fjordane, Norway", "Hardangerfjord, Hardanger, Norway", "Reynisfjara Beach, Vik, Iceland",
    "Golden Circle, Iceland", "Zakopane Tatra Mountains, Zakopane, Poland", "Meteora Monastery Viewpoint, Kalambaka, Greece",
    "Sintra National Palace, Sintra, Portugal", "Pena Park, Sintra, Portugal", "Montjuïc Castle, Barcelona, Spain",
    "Camp Nou Stadium, Barcelona, Spain", "Retiro Park, Madrid, Spain", "Toledo Old Town, Toledo, Spain",
    "Segovia Aqueduct, Segovia, Spain", "Alcázar of Segovia, Segovia, Spain", "Ronda Bridge, Ronda, Spain",
    "Alcázar of Seville, Seville, Spain", "Costa Brava Coastline, Girona, Spain", "Ibiza Old Town, Ibiza, Spain",
    "Mallorca Cathedral, Palma, Spain", "Teide National Park, Tenerife, Spain", "Pico del Teide, Tenerife, Spain",
    "Canary Sand Dunes, Gran Canaria, Spain", "Madeira Cliffs, Madeira, Portugal", "Cabo da Roca, Sintra, Portugal",
    "Douro River Valley, Douro, Portugal", "Fátima Sanctuary, Fátima, Portugal", "Guimarães Castle, Guimarães, Portugal",
    "Aveiro Canals, Aveiro, Portugal", "Azores Sete Cidades Lake, Azores, Portugal", "Azores Lagoa do Fogo, Azores, Portugal",
    "Azores Furnas Lake, Azores, Portugal", "Azores Hot Springs, Azores, Portugal", "Brussels Grand Place, Brussels, Belgium",
    "Atomium, Brussels, Belgium", "Bruges Canals, Bruges, Belgium", "Belfry of Bruges, Bruges, Belgium",
    "Ghent Castle of the Counts, Ghent, Belgium", "Antwerp Cathedral, Antwerp, Belgium", "Luxembourg Old Town, Luxembourg City, Luxembourg",
    "Bock Casemates, Luxembourg City, Luxembourg", "Schengen Village, Schengen, Luxembourg", "Rotterdam Cube Houses, Rotterdam, Netherlands",
    "Kinderdijk Windmills, Kinderdijk, Netherlands", "Rijksmuseum, Amsterdam, Netherlands", "Anne Frank House, Amsterdam, Netherlands",
    "Van Gogh Museum, Amsterdam, Netherlands", "Keukenhof Gardens, Lisse, Netherlands", "Zaanse Schans Windmills, Zaanse Schans, Netherlands",
    "Giethoorn Village, Giethoorn, Netherlands", "Maastricht Old Town, Maastricht, Netherlands", "Utrecht Dom Tower, Utrecht, Netherlands",
    "Delft Old Town, Delft, Netherlands", "Alkmaar Cheese Market, Alkmaar, Netherlands", "Haarlem Old Town, Haarlem, Netherlands",
    "Marken Village, Marken, Netherlands", "Volendam Harbor, Volendam, Netherlands", "Texel Island, Texel, Netherlands",
    "Wadden Sea Islands, Wadden Sea, Netherlands", "Black Forest, Baden-Württemberg, Germany", "Zugspitze Mountain, Bavaria, Germany",
    "Königssee Lake, Bavaria, Germany", "Berchtesgaden National Park, Bavaria, Germany", "Rothenburg ob der Tauber Old Town, Rothenburg, Germany",
    "Wartburg Castle, Eisenach, Germany", "Bamberg Old Town, Bamberg, Germany", "Blue Mosque (Sultanahmet Camii), Istanbul, Türkiye",
    "Topkapi Palace, Istanbul, Türkiye", "Basilica Cistern, Istanbul, Türkiye", "Grand Bazaar, Istanbul, Türkiye",
    "Dolmabahce Palace, Istanbul, Türkiye", "Galata Tower, Istanbul, Türkiye", "Istiklal Street, Istanbul, Türkiye",
    "Bosphorus Bridge, Istanbul, Türkiye", "Ortakoy Mosque, Istanbul, Türkiye", "Maiden’s Tower, Istanbul, Türkiye",
    "Rumeli Fortress, Istanbul, Türkiye", "Balat Historic District, Istanbul, Türkiye", "Princes Islands, Istanbul, Türkiye",
    "Miniaturk Park, Istanbul, Türkiye", "Pierre Loti Hill, Istanbul, Türkiye", "Beylerbeyi Palace, Istanbul, Türkiye",
    "Yildiz Park, Istanbul, Türkiye", "Suleymaniye Mosque, Istanbul, Türkiye", "Chora Church, Istanbul, Türkiye",
    "Ephesus Ancient City, Izmir, Türkiye", "House of Virgin Mary, Izmir, Türkiye", "Sirince Village, Izmir, Türkiye",
    "Pergamon Ancient City, Bergama, Izmir, Türkiye", "Asclepion, Bergama, Izmir, Türkiye", "Kadifekale, Izmir, Türkiye",
    "Kordon Promenade, Izmir, Türkiye", "Cesme Marina, Izmir, Türkiye", "Alacati Windmills, Izmir, Türkiye",
    "Alacati Streets, Izmir, Türkiye", "Ilica Beach, Cesme, Izmir, Türkiye", "Foça Old Town, Izmir, Türkiye",
    "Karaburun Coast, Izmir, Türkiye", "Sığacık Village, Seferihisar, Izmir, Türkiye", "Teos Ancient City, Izmir, Türkiye",
    "Goreme Open Air Museum, Nevsehir, Türkiye", "Uchisar Castle, Nevsehir, Türkiye", "Derinkuyu Underground City, Nevsehir, Türkiye",
    "Kaymakli Underground City, Nevsehir, Türkiye", "Ihlara Valley, Aksaray, Türkiye", "Selime Monastery, Aksaray, Türkiye",
    "Hierapolis Ancient City, Denizli, Türkiye", "Laodicea Ancient City, Denizli, Türkiye", "Aspendos Theatre, Antalya, Türkiye",
    "Perge Ancient City, Antalya, Türkiye", "Side Ancient City, Antalya, Türkiye", "Manavgat Waterfall, Antalya, Türkiye",
    "Duden Waterfalls, Antalya, Türkiye", "Olympos Ancient City, Antalya, Türkiye", "Cirali Beach, Antalya, Türkiye",
    "Yanartas (Chimera Flames), Antalya, Türkiye", "Phaselis Ancient City, Antalya, Türkiye", "Konyaalti Beach, Antalya, Türkiye",
    "Lara Beach, Antalya, Türkiye", "Kaleici Old Town, Antalya, Türkiye", "Termessos Ancient City, Antalya, Türkiye",
    "Bodrum Castle, Mugla, Türkiye", "Mausoleum at Halicarnassus, Bodrum, Türkiye", "Bodrum Marina, Mugla, Türkiye",
    "Fethiye Oludeniz Lagoon, Mugla, Türkiye", "Butterfly Valley, Fethiye, Mugla, Türkiye", "Saklikent Canyon, Mugla, Türkiye",
    "Kayakoy Ghost Village, Mugla, Türkiye", "Dalyan River, Mugla, Türkiye", "Iztuzu Beach, Mugla, Türkiye",
    "Marmaris Marina, Mugla, Türkiye", "Datca Peninsula, Mugla, Türkiye", "Knidos Ancient City, Mugla, Türkiye",
    "Nemrut Statues, Adiyaman, Türkiye", "Sumela Monastery, Trabzon, Türkiye", "Uzungol Lake, Trabzon, Türkiye",
    "Hagia Sophia Trabzon, Trabzon, Türkiye", "Ayder Plateau, Rize, Türkiye", "Firtina Valley, Rize, Türkiye",
    "Safranbolu Old Town, Karabuk, Türkiye", "Tokatli Canyon, Safranbolu, Türkiye", "Amasra Harbor, Bartin, Türkiye",
    "Abant Lake, Bolu, Türkiye", "Yedigoller National Park, Bolu, Türkiye", "Uludag Mountain, Bursa, Türkiye",
    "Bursa Grand Mosque, Bursa, Türkiye", "Cumalikizik Village, Bursa, Türkiye", "Troy Ancient City, Canakkale, Türkiye",
    "Gallipoli Peninsula, Canakkale, Türkiye", "Assos Ancient City, Canakkale, Türkiye", "Mount Ararat, Agri, Türkiye",
    "Ishak Pasha Palace, Agri, Türkiye", "Ani Ruins, Kars, Türkiye", "Lake Cildir, Kars, Türkiye",
    "Lake Van, Van, Türkiye", "Akdamar Island Church, Van, Türkiye", "Hasankeyf Ruins, Batman, Türkiye",
    "Mardin Old Town, Mardin, Türkiye", "Dara Ancient City, Mardin, Türkiye", "Sanliurfa Balikli Gol, Sanliurfa, Türkiye",
    "Gobekli Tepe, Sanliurfa, Türkiye", "Harran Houses, Sanliurfa, Türkiye", "Manneken Pis, Brussels, Belgium",
    "Grand Place, Brussels, Belgium", "Bruges Belfry, Bruges, Belgium", "Canals of Bruges, Bruges, Belgium",
    "Luxembourg Gardens, Paris, France", "Palais Garnier, Paris, France", "Montmartre District, Paris, France",
    "Cliffs of Étretat, Normandy, France", "Pont Neuf, Paris, France", "Pont Alexandre III, Paris, France",
    "Saint-Malo Old Town, Saint-Malo, France", "Piazza del Duomo, Florence, Italy", "Piazza della Signoria, Florence, Italy",
    "Boboli Gardens, Florence, Italy", "Rialto Market, Venice, Italy", "Santa Maria della Salute, Venice, Italy",
    "Montjuïc Hill, Barcelona, Spain", "Barcelona Cathedral, Barcelona, Spain", "Palau de la Música Catalana, Barcelona, Spain",
    "Toledo Alcazar, Toledo, Spain", "Segovia Cathedral, Segovia, Spain", "Ronda Old Town, Ronda, Spain",
    "Ibiza Dalt Vila, Ibiza, Spain", "La Concha Beach, San Sebastián, Spain", "Sintra Moorish Castle, Sintra, Portugal",
    "National Palace of Sintra, Sintra, Portugal", "Monserrate Palace, Sintra, Portugal", "Ribeira Square, Porto, Portugal",
    "Dom Luís I Bridge, Porto, Portugal", "Clérigos Tower, Porto, Portugal", "Akershus Fortress, Oslo, Norway",
    "Vigeland Sculpture Park, Oslo, Norway", "Bryggen Wharf, Bergen, Norway", "Fjaerland Glacier Museum, Fjaerland, Norway",
    "Helsinki Market Square, Helsinki, Finland", "Temppeliaukio Church, Helsinki, Finland", "Royal Palace Stockholm, Stockholm, Sweden",
    "Skansen Open-Air Museum, Stockholm, Sweden", "Winkel 43, Amsterdam, Netherlands", "De Kas, Amsterdam, Netherlands",
    "Restaurant Vinkeles, Amsterdam, Netherlands", "Ciel Bleu, Amsterdam, Netherlands", "Restaurant Breda, Amsterdam, Netherlands",
    "FG Restaurant, Rotterdam, Netherlands", "Parkheuvel, Rotterdam, Netherlands", "De Librije, Zwolle, Netherlands",
    "Pure C, Cadzand, Netherlands", "The White Room, Amsterdam, Netherlands", "RIJKS®, Amsterdam, Netherlands",
    "Daalder, Amsterdam, Netherlands", "Restaurant 212, Amsterdam, Netherlands", "Bistro Belcampo, Haarlem, Netherlands",
    "EightyEight, Amsterdam, Netherlands", "De Bokkedoorns, Overveen, Netherlands", "Senses Restaurant, The Hague, Netherlands",
    "Oud Sluis, Sluis, Netherlands", "Bridges, Amsterdam, Netherlands", "Van Speyk, Amsterdam, Netherlands",
    "Hakkasan, Frankfurt, Germany", "Restaurant Tim Raue, Berlin, Germany", "Facil, Berlin, Germany",
    "Nobelhart & Schmutzig, Berlin, Germany", "Lorenz Adlon Esszimmer, Berlin, Germany", "Rutz, Berlin, Germany",
    "Pauly Saal, Berlin, Germany", "Schwarzwaldstube, Baiersbronn, Germany", "Bareiss, Baiersbronn, Germany",
    "Restaurant Überfahrt, Rottach-Egern, Germany", "Aroma, Munich, Germany", "Tantris, Munich, Germany",
    "Dallmayr, Munich, Germany", "Restaurant Königshof, Munich, Germany", "Aumeister, Munich, Germany",
    "The Grill, Munich, Germany", "Vox Restaurant, Munich, Germany", "Historische Altstadthof, Munich, Germany",
    "Zum Augustiner, Munich, Germany", "Der Adler, Mainz, Germany", "Lumen, Frankfurt, Germany",
    "Seven Swans, Frankfurt, Germany", "Restaurant Villa Merton, Frankfurt, Germany", "SRA BUA by Tim Raue, Frankfurt, Germany",
    "Apfelwein Wagner, Frankfurt, Germany", "Zur Golden Krone, Frankfurt, Germany", "Plaza Bar Restaurant, Hamburg, Germany",
    "Haerlin, Hamburg, Germany", "The Table Kevin Fehling, Hamburg, Germany", "Bullerei, Hamburg, Germany",
    "Tschebull, Hamburg, Germany", "Vlet in der Speicherstadt, Hamburg, Germany", "Brasserie 8½, Dusseldorf, Germany",
    "Berens am Kai, Dusseldorf, Germany", "Nagaya, Dusseldorf, Germany", "Im Schiffchen, Dusseldorf, Germany",
    "Agence de Cuisine, Dusseldorf, Germany", "Gasthaus Hohenwart, Murnau, Germany", "Zum Schwabo, Freiburg, Germany",
    "Markthalle Stuttgart, Stuttgart, Germany", "Cube Restaurant, Stuttgart, Germany", "Ochs'n Willi, Stuttgart, Germany",
    "Restaurant Délice, Stuttgart, Germany", "Alte Kanzlei, Regensburg, Germany", "Wurstkuchl, Regensburg, Germany",
    "Gasthof Fraundorfer, Regensburg, Germany", "Gasthaus zur Linde, Bavaria, Germany", "Kochzimmer, Hannover, Germany",
    "Osteria Francescana, Modena, Italy", "La Pergola, Rome, Italy", "Enoteca Pinchiorri, Florence, Italy",
    "Uliassi, Senigallia, Italy", "Da Vittorio, Brusaporto, Italy", "Reale, Castel di Sangro, Italy",
    "Il Luogo di Aimo e Nadia, Milan, Italy", "Dal Pescatore, Canneto sull’Oglio, Italy", "Piazza Duomo, Alba, Italy",
    "Cracco, Milan, Italy", "Il Ristorante Trussardi alla Scala, Milan, Italy", "Da Enzo al 29, Rome, Italy",
    "Roscioli, Rome, Italy", "Armando al Pantheon, Rome, Italy", "Antica Pizzeria da Michele, Naples, Italy",
    "Sorbillo, Naples, Italy", "Pepe in Grani, Caiazzo, Italy", "Osteria Le Logge, Siena, Italy",
    "La Cantina del Gallo Nero, Florence, Italy", "Il Palagio, Florence, Italy", "Enosteria Lipen, Val di Non, Italy",
    "Al Sorriso, Soriso, Italy", "Il Pellicano, Porto Ercole, Italy", "La Madia, Licata, Italy",
    "Lido 84, Gardone Riviera, Italy", "Locanda Locatelli, Milan, Italy", "Ristorante Cracco, Milan, Italy",
    "Al Ceppo, Florence, Italy", "Ristorante Arnolfo, Colle di Val d’Elsa, Italy", "Il Comandante, Naples, Italy",
    "Gagini, Palermo, Italy", "Perbellini, Verona, Italy", "Osteria del Pescatore, Marotta, Italy",
    "Casa Vissani, Baschi, Italy", "La Tana Gourmet, Ceglie Messapica, Italy", "Ristorante Da Caino, Montemerano, Italy",
    "La Credenza, San Maurizio Canavese, Italy", "Casa Perbellini, Verona, Italy", "Lume, Milan, Italy",
    "Il Gatto Nero, Cernobbio, Italy", "Le Calandre, Rubano, Italy", "Metamorfosi, Rome, Italy",
    "Per Me, Rome, Italy", "Osteria del Borgo, Verona, Italy", "Comme Chez Soi, Brussels, Belgium",
    "Le Chalet de la Forêt, Brussels, Belgium", "Bozar Restaurant, Brussels, Belgium", "La Villa in the Sky, Brussels, Belgium",
    "Restaurant Vincent, Brussels, Belgium", "Brasserie de la Ville, Brussels, Belgium", "Le Rabassier, Brussels, Belgium",
    "Woodpecker, Brussels, Belgium", "Noordzee Mer du Nord, Brussels, Belgium", "La Roue d’Or, Brussels, Belgium",
    "Chez Léon, Brussels, Belgium", "L’Idiot du Village, Brussels, Belgium", "Brasserie Georges, Liège, Belgium",
    "Le Coq aux Champs, Waterloo, Belgium", "Nuance, Boom, Belgium", "Pastorale, Reet, Belgium",
    "Hof van Cleve, Kruishoutem, Belgium", "De Karmeliet, Bruges, Belgium", "Bistro Bruut, Bruges, Belgium",
    "Den Dyver, Bruges, Belgium", "Park Restaurant, Knokke-Heist, Belgium", "La Villa Lorraine, Brussels, Belgium",
    "Le Châlet de la Forêt, Brussels, Belgium", "La Truffe Noire, Brussels, Belgium", "Le Bistro, Namur, Belgium",
    "La Paix, Liège, Belgium", "Les Eleveurs, Liège, Belgium", "L’Air du Temps, Éghezée, Belgium",
    "Sea Grill, Brussels, Belgium", "La Quincaillerie, Brussels, Belgium", "Pajot, Ghent, Belgium",
    "Vrijmoed, Ghent, Belgium", "De Graslei, Ghent, Belgium", "Oud Sluis, Sluis, Belgium",
    "Bistro Refter, Brussels, Belgium", "L’Ecailler du Palais Royal, Brussels, Belgium", "Le Pain Quotidien, Brussels, Belgium",
    "T Kelderke, Brussels, Belgium", "La Villa des Roses, Brussels, Belgium", "L’Atelier de Jean-Luc Rabanel, Brussels, Belgium",
    "Le Chou de Bruxelles, Brussels, Belgium", "Les Brigittines, Brussels, Belgium", "Le Pigeon Noir, Brussels, Belgium",
    "De Jonkman, Bruges, Belgium", "Maison Dandoy, Brussels, Belgium", "Liège Waffles, Brussels, Belgium",
    "Frit Flagey, Brussels, Belgium", "Fritland, Brussels, Belgium", "Maison Antoine, Brussels, Belgium",
    "Le Funambule, Brussels, Belgium", "Frituur 't Brugse Friethuis, Bruges, Belgium", "Chez Albert, Bruges, Belgium",
    "Frituur Number One, Ghent, Belgium", "Chez Albert, Brussels, Belgium", "La Belgique Gourmande, Brussels, Belgium",
    "Max Chocolatier, Brussels, Belgium", "La Fabrique, Brussels, Belgium", "El Celler de Can Roca, Girona, Spain",
    "Arzak, San Sebastián, Spain", "Akelarre, San Sebastián, Spain", "Mugaritz, Errenteria, Spain",
    "Tickets, Barcelona, Spain", "Disfrutar, Barcelona, Spain", "Lasarte, Barcelona, Spain",
    "ABaC, Barcelona, Spain", "Can Majó, Barcelona, Spain", "Cal Pep, Barcelona, Spain",
    "Casa Mono, Madrid, Spain", "DiverXO, Madrid, Spain", "Sobrino de Botín, Madrid, Spain",
    "Ramon Freixa Madrid, Madrid, Spain", "La Trainera, Madrid, Spain", "El Club Allard, Madrid, Spain",
    "Casa Lucio, Madrid, Spain", "Bar Cañete, Barcelona, Spain", "Quimet & Quimet, Barcelona, Spain",
    "Bodega 1900, Barcelona, Spain", "Cervecería Catalana, Barcelona, Spain", "La Boqueria Market, Barcelona, Spain",
    "Botín, Madrid, Spain", "Asador Etxebarri, Axpe, Spain", "Casa Paco, Seville, Spain",
    "El Rinconcillo, Seville, Spain", "Abades Triana, Seville, Spain", "La Azotea, Seville, Spain",
    "Bar El Comercio, Seville, Spain", "Bodega Santa Cruz, Seville, Spain", "Bar La Plata, Barcelona, Spain",
    "El Xampanyet, Barcelona, Spain", "Casa Alberto, Madrid, Spain", "La Venencia, Madrid, Spain",
    "Cervecería La Sureña, Madrid, Spain", "El Sur, Madrid, Spain", "Taberna del Alabardero, Madrid, Spain",
    "Restaurante Echaurren, Ezcaray, Spain", "Arrop, Madrid, Spain", "Bodegas Castañeda, Granada, Spain",
    "Los Diamantes, Seville, Spain", "La Bombeta, Barcelona, Spain", "Xiringuito Escribà, Barcelona, Spain",
    "Bar Tomas, Barcelona, Spain", "Can Solé, Barcelona, Spain", "El Quim de la Boqueria, Barcelona, Spain",
    "El Tapeo de Cervantes, Madrid, Spain", "Casa Morales, Seville, Spain", "Taberna Salinas, Seville, Spain",
    "Bodega La Palma, Madrid, Spain", "Bodeguita El Gallo, Seville, Spain", "Restaurante Etxanobe, Bilbao, Spain",
    "Zuberoa, Oiartzun, Spain", "Belcanto, Lisbon, Portugal", "Alma, Lisbon, Portugal",
    "Feitoria, Lisbon, Portugal", "100 Maneiras, Lisbon, Portugal", "Ramiro, Lisbon, Portugal",
    "Cervejaria Trindade, Lisbon, Portugal", "Pasteis de Belem, Lisbon, Portugal", "A Cevicheria, Lisbon, Portugal",
    "Sea Me, Lisbon, Portugal", "Taberna da Rua das Flores, Lisbon, Portugal", "Cantinho do Avillez, Lisbon, Portugal",
    "O Faia, Lisbon, Portugal", "Mini Bar Teatro, Lisbon, Portugal", "Prado, Lisbon, Portugal",
    "Restaurante Eleven, Lisbon, Portugal", "Café A Brasileira, Lisbon, Portugal", "Mercado da Ribeira, Lisbon, Portugal",
    "Casa de Pasto, Lisbon, Portugal", "O Talho, Lisbon, Portugal", "DOP, Porto, Portugal",
    "Cantinho do Avillez Porto, Porto, Portugal", "Pedro Lemos, Porto, Portugal", "Adega São Nicolau, Porto, Portugal",
    "Casa Guedes, Porto, Portugal", "Brasão Cervejaria Aliados, Porto, Portugal", "Café Majestic, Porto, Portugal",
    "Taberna dos Mercadores, Porto, Portugal", "Restaurante Pedro dos Frangos, Porto, Portugal", "A Cozinha do Manel, Porto, Portugal",
    "Rui Paula DOP, Porto, Portugal", "Cantinho das Freiras, Lisbon, Portugal", "O Lavrador, Sintra, Portugal",
    "Tascantiga, Lisbon, Portugal", "Solar dos Presuntos, Lisbon, Portugal", "Marisqueira Uma, Lisbon, Portugal",
    "Sea Me Peixaria Moderna, Lisbon, Portugal", "Pastéis de Nata Manteigaria, Lisbon, Portugal", "Fado na Morgadinha, Lisbon, Portugal",
    "O Diplomata, Lisbon, Portugal", "Café Guarany, Porto, Portugal", "Mercado do Bolhão, Porto, Portugal",
    "Bacalhau & Companhia, Porto, Portugal", "Taberna Santo António, Porto, Portugal", "Cantinho do Avillez Lisboa, Lisbon, Portugal",
    "O Pescador, Porto, Portugal", "Brasão Aliados, Porto, Portugal", "Restaurante Caféína, Lisbon, Portugal",
    "Restaurante Tágide, Lisbon, Portugal", "Le Meurice, Paris, France", "L'Arpège, Paris, France",
    "Le Cinq, Paris, France", "Epicure, Paris, France", "Septime, Paris, France",
    "Le Jules Verne, Paris, France", "Guy Savoy, Paris, France", "Pierre Gagnaire, Paris, France",
    "La Tour d’Argent, Paris, France", "Le Bristol Paris, Paris, France", "L’Ambroisie, Paris, France",
    "La Grande Cascade, Paris, France", "Le Chateaubriand, Paris, France", "L'Atelier de Joël Robuchon, Paris, France",
    "Pierre Hermé, Paris, France", "Ladurée, Paris, France", "Angelina, Paris, France",
    "Café de Flore, Paris, France", "Les Deux Magots, Paris, France", "Benoit, Paris, France",
    "Le Comptoir du Relais, Paris, France", "Le Procope, Paris, France", "Au Pied de Cochon, Paris, France",
    "Le Relais de l’Entrecôte, Paris, France", "La Fontaine de Mars, Paris, France", "Chez L’Ami Jean, Paris, France",
    "Le Pré Catelan, Paris, France", "Les Crayères, Reims, France", "Maison Lameloise, Chagny, France",
    "Le Clos des Sens, Annecy, France", "Restaurant Paul Bocuse, Lyon, France", "La Mère Brazier, Lyon, France",
    "Têtedoie, Lyon, France", "Le Gourmet de Sèze, Lyon, France", "Les Trois Dômes, Lyon, France",
    "La Pyramide, Vienne, France", "Château Cordeillan-Bages, Pauillac, France", "Mirazur, Menton, France",
    "Restaurant Jan, Paris, France", "Le Bernardin, Paris, France", "Le Taillevent, Paris, France",
    "Le Grand Véfour, Paris, France", "Alléno Paris au Pavillon Ledoyen, Paris, France", "Hôtel de Crillon – L'Écrin, Paris, France",
    "Restaurant Guy Savoy, Paris, France", "Le Meurice Alain Ducasse, Paris, France", "L’Oustau de Baumanière, Les Baux-de-Provence, France",
    "La Vague d’Or, Saint-Tropez, France", "L’Auberge du Pont de Collonges, Collonges-au-Mont-d’Or, France", "Le Jardin des Sens, Montpellier, France",
    "Funky Gourmet, Athens, Greece", "Varoulko Seaside, Athens, Greece", "Spondi, Athens, Greece",
    "Hytra, Athens, Greece", "GB Roof Garden, Athens, Greece", "Tzitzikas kai Mermigas, Athens, Greece",
    "Kuzina, Athens, Greece", "Athiri, Athens, Greece", "Oineas Restaurant, Athens, Greece",
    "Avocado, Athens, Greece", "Ta Karamanlidika tou Fani, Athens, Greece", "Ergon Athens, Athens, Greece",
    "Mani Mani, Athens, Greece", "Couleur Locale, Athens, Greece", "O Kostas, Athens, Greece",
    "Savvas Souvlaki, Athens, Greece", "Lukumades, Athens, Greece", "Kalamaki Bar, Athens, Greece",
    "To Kafeneio, Athens, Greece", "Nolan, Athens, Greece", "Ouzeri tou Laki, Athens, Greece",
    "Strofi, Athens, Greece", "Taverna Klimataria, Athens, Greece", "I Kriti, Athens, Greece",
    "Balcony Restaurant, Athens, Greece", "Meliartos, Athens, Greece", "Melilotos, Athens, Greece",
    "Vezene, Athens, Greece", "Thalassina, Athens, Greece", "Paradosiako, Athens, Greece",
    "Oineas, Athens, Greece", "Taverna tou Psirri, Athens, Greece", "Lithos, Athens, Greece",
    "Naoussa, Athens, Greece", "Zahoulis, Athens, Greece", "Koursaros, Athens, Greece",
    "Barrel, Athens, Greece", "Fresko, Athens, Greece", "Taverna Akrogiali, Athens, Greece",
    "To Steki tou Ilia, Athens, Greece", "Kiki’s Tavern, Mykonos, Greece", "M-eating, Mykonos, Greece",
    "Avra Restaurant, Athens, Greece", "To Kafeneio, Santorini, Greece", "Metaxi Mas, Santorini, Greece",
    "Selene, Santorini, Greece", "1800, Santorini, Greece", "Argo, Athens, Greece",
    "Çiya Sofrası, Istanbul, Türkiye", "Pandeli Restaurant, Istanbul, Türkiye", "Hamdi Restaurant, Istanbul, Türkiye",
    "Saray Muhallebicisi, Istanbul, Türkiye", "Karaköy Lokantası, Istanbul, Türkiye", "Mikla, Istanbul, Türkiye",
    "360 Istanbul, Istanbul, Türkiye", "Balıkçı Sabahattin, Istanbul, Türkiye", "Asitane, Istanbul, Türkiye",
    "Konyalı, Istanbul, Türkiye", "Tarihi Sultanahmet Köftecisi, Istanbul, Türkiye", "Vefa Bozacısı, Istanbul, Türkiye",
    "Şampiyon Kokoreç, Istanbul, Türkiye", "Beyti, Istanbul, Türkiye", "Çınaraltı Çay Bahçesi, Istanbul, Türkiye",
    "Deniz Restaurant, Istanbul, Türkiye", "Kebapçı İskender, Bursa, Türkiye", "Hisarönü Kebabçısı, Bursa, Türkiye",
    "Kebapçı Halil, Gaziantep, Türkiye", "İmam Çağdaş, Gaziantep, Türkiye", "Bayramoğlu Döner, Izmir, Türkiye",
    "Topçu Kebap, Izmir, Türkiye", "Deniz Restaurant, Izmir, Türkiye", "Kordon Balıkçısı, Izmir, Türkiye",
    "Saklı Bahçe, Antalya, Türkiye", "7 Mehmet, Antalya, Türkiye", "Seraser Fine Dining, Antalya, Türkiye",
    "Piyade Kebap, Ankara, Türkiye", "Trilye Restaurant, Ankara, Türkiye", "Meşhur Tavacı Recep Usta, Ankara, Türkiye",
    "Firin Express, Bodrum, Türkiye", "Orfoz Restaurant, Bodrum, Türkiye", "Kısmet Restaurant, Bodrum, Türkiye",
    "Seten Restaurant, Kapadokya, Türkiye", "Topdeck Cave Restaurant, Kapadokya, Türkiye", "Ziggy Café, Kapadokya, Türkiye",
    "Saklı Konak, Kapadokya, Türkiye", "Saklı Bahçe, Alanya, Türkiye", "Doy Doy Restaurant, Alanya, Türkiye",
    "Kleopatra Balık, Alanya, Türkiye", "Firin Express, Marmaris, Türkiye", "Okyanus Restaurant, Marmaris, Türkiye",
    "Turkuaz Restaurant, Marmaris, Türkiye", "Kebapçı Halil, Şanlıurfa, Türkiye", "Çiğ Köfteci Halil Usta, Şanlıurfa, Türkiye",
    "Balıklıgöl Restaurant, Şanlıurfa, Türkiye", "Kebapçı Yaşar, Adana, Türkiye", "Ciğerci Hulusi, Adana, Türkiye",
    "Kebapçı Halil Usta, Adana, Türkiye", "Mlýnec, Prague, Czech Republic", "La Degustation Bohême Bourgeoise, Prague, Czech Republic",
    "Field Restaurant, Prague, Czech Republic", "Eska, Prague, Czech Republic", "Kampa Park, Prague, Czech Republic",
    "Café Savoy, Prague, Czech Republic", "U Modré Kachničky, Prague, Czech Republic", "Lokál Dlouhááá, Prague, Czech Republic",
    "U Fleků, Prague, Czech Republic", "Restaurace Mlejnice, Prague, Czech Republic", "Café Louvre, Prague, Czech Republic",
    "Kuchyň, Prague, Czech Republic", "Pivovarský dům, Prague, Czech Republic", "U Kroka, Prague, Czech Republic",
    "Sansho, Prague, Czech Republic", "Café Imperial, Prague, Czech Republic", "Potrefená Husa, Prague, Czech Republic",
    "V Kolkovně, Prague, Czech Republic", "U Glaubiců, Prague, Czech Republic", "Kampa Cafe, Prague, Czech Republic",
    "St. Martin, Prague, Czech Republic", "U Malířů, Prague, Czech Republic", "Pivovarský klub, Prague, Czech Republic",
    "Na Kopci, Brno, Czech Republic", "Stopkova Plzeňská Pivnice, Brno, Czech Republic", "Výčep Na Stojáka, Brno, Czech Republic",
    "Špalíček, Brno, Czech Republic", "Restaurace Pegas, Brno, Czech Republic", "U Dvou Koček, Brno, Czech Republic",
    "Restaurant Le Terroir, Brno, Czech Republic", "Cafe Placzek, Brno, Czech Republic", "Papa’s Living Restaurant, Český Krumlov, Czech Republic",
    "Le Jardin, Český Krumlov, Czech Republic", "Krcma v Satlavske Ulici, Český Krumlov, Czech Republic", "Na Louzi, Český Krumlov, Czech Republic",
    "Restaurant Konvice, Český Krumlov, Czech Republic", "Hospoda Na Louzi, Český Krumlov, Czech Republic", "Eggenberg Brewery Restaurant, Český Krumlov, Czech Republic",
    "Café Štrúdl, Prague, Czech Republic", "V Zátiší, Prague, Czech Republic", "Café Slavia, Prague, Czech Republic",
    "Lokál U Bílé kuželky, Prague, Czech Republic", "U Prince, Prague, Czech Republic", "Pivnice U Tri Ruzi, Prague, Czech Republic",
    "Naše Maso, Prague, Czech Republic", "Kronenhalle, Zurich, Switzerland", "Restaurant Zeughauskeller, Zurich, Switzerland",
    "Hiltl, Zurich, Switzerland", "Confiserie Sprüngli, Zurich, Switzerland", "Pavillon, Zurich, Switzerland",
    "LaSalle, Zurich, Switzerland", "Restaurant Razzia, Zurich, Switzerland", "Fraumünster Restaurant, Zurich, Switzerland",
    "Chäsalp, Zurich, Switzerland", "Babu's Bakery & Coffeehouse, Zurich, Switzerland", "Brasserie Lipp, Geneva, Switzerland",
    "Café du Soleil, Geneva, Switzerland", "Les Armures, Geneva, Switzerland", "Bayview by Michel Roth, Geneva, Switzerland",
    "Le Chat-Botté, Geneva, Switzerland", "Café Papon, Geneva, Switzerland", "Chez Ma Cousine, Geneva, Switzerland",
    "Restaurant Le Floris, Geneva, Switzerland", "La Table d’Edgard, Lausanne, Switzerland", "Anne-Sophie Pic at Beau-Rivage, Lausanne, Switzerland",
    "Brasserie de Montbenon, Lausanne, Switzerland", "Café de Grancy, Lausanne, Switzerland", "Restaurant du Château d’Ouchy, Lausanne, Switzerland",
    "Le Nomade, Lausanne, Switzerland", "Restaurant Schlüsselzunft, Basel, Switzerland", "Cheval Blanc, Basel, Switzerland",
    "Les Quatre Saisons, Basel, Switzerland", "Volkshaus Basel, Basel, Switzerland", "Klara, Basel, Switzerland",
    "Restaurant Stucki, Basel, Switzerland", "Le Café de Paris, Lausanne, Switzerland", "Restaurant Le Chatelain, Zurich, Switzerland",
    "Boccone, Zurich, Switzerland", "Mesa, Zurich, Switzerland", "Pinte Besson, Lausanne, Switzerland",
    "Le Pont de Brent, Brent, Switzerland", "Gasthof zum Gupf, Zurich, Switzerland", "Zum Kropf, Zurich, Switzerland",
    "Café Sprüngli, Zurich, Switzerland", "Ristorante Bindella, Zurich, Switzerland", "Blinde Kuh, Zurich, Switzerland",
    "Markthalle, Basel, Switzerland", "Restaurant Kunsthalle, Basel, Switzerland", "Gasthof zum Goldenen Sternen, Basel, Switzerland",
    "Auberge de l’Onde, Vevey, Switzerland", "Restaurant Le Deck, Geneva, Switzerland",
    "Chez Philippe, Geneva, Switzerland", "Restaurant Le Chat Botté, Geneva, Switzerland"];
