export const TOURIST_LOCATIONS = [
    "Colosseum, Rome, Italy", "Eiffel Tower, Paris, France", "Statue of Liberty, New York, USA",
    "Great Wall, Beijing, China", "Taj Mahal, Agra, India", "Machu Picchu, Cusco, Peru",
    "Christ the Redeemer, Rio de Janeiro, Brazil", "Petra, Petra, Jordan", "Angkor Wat, Siem Reap, Cambodia",
    "Pyramids of Giza, Giza, Egypt", "Big Ben, London, United Kingdom", "Buckingham Palace, London, United Kingdom",
    "Louvre Museum, Paris, France", "Notre Dame Cathedral, Paris, France", "Sagrada Familia, Barcelona, Spain",
    "Park Güell, Barcelona, Spain", "Alhambra, Granada, Spain", "Acropolis, Athens, Greece",
    "Parthenon, Athens, Greece", "Santorini Caldera, Santorini, Greece", "Mount Fuji, Honshu, Japan",
    "Fushimi Inari Shrine, Kyoto, Japan", "Kinkaku-ji, Kyoto, Japan", "Tokyo Tower, Tokyo, Japan",
    "Shibuya Crossing, Tokyo, Japan", "Burj Khalifa, Dubai, UAE", "Palm Jumeirah, Dubai, UAE",
    "Sheikh Zayed Grand Mosque, Abu Dhabi, UAE", "Blue Mosque, Istanbul, Türkiye", "Hagia Sophia, Istanbul, Türkiye",
    "Cappadocia Fairy Chimneys, Nevşehir, Türkiye", "Pamukkale Travertines, Denizli, Türkiye", "Mount Nemrut, Adıyaman, Türkiye",
    "Stonehenge, Wiltshire, United Kingdom", "Tower Bridge, London, United Kingdom", "British Museum, London, United Kingdom",
    "Edinburgh Castle, Edinburgh, United Kingdom", "Neuschwanstein Castle, Bavaria, Germany", "Brandenburg Gate, Berlin, Germany",
    "Cologne Cathedral, Cologne, Germany", "Prague Castle, Prague, Czech Republic", "Charles Bridge, Prague, Czech Republic",
    "Schönbrunn Palace, Vienna, Austria", "Hallstatt Village, Hallstatt, Austria", "Leaning Tower of Pisa, Pisa, Italy",
    "St Peter’s Basilica, Vatican City, Vatican City", "Trevi Fountain, Rome, Italy", "Pantheon, Rome, Italy",
    "Pompeii Ruins, Pompeii, Italy", "Cinque Terre, Liguria, Italy", "Milan Cathedral, Milan, Italy",
    "Venice Grand Canal, Venice, Italy", "Doge’s Palace, Venice, Italy", "Mont Saint-Michel, Normandy, France",
    "Palace of Versailles, Versailles, France", "Arc de Triomphe, Paris, France", "Sacré-Cœur, Paris, France",
    "Disneyland Park, Anaheim, USA", "Golden Gate Bridge, San Francisco, USA", "Alcatraz Island, San Francisco, USA",
    "Grand Canyon, Arizona, USA", "Yellowstone National Park, Wyoming, USA", "Times Square, New York, USA",
    "Central Park, New York, USA", "Empire State Building, New York, USA", "Hollywood Sign, Los Angeles, USA",
    "Griffith Observatory, Los Angeles, USA", "Las Vegas Strip, Las Vegas, USA", "Niagara Falls, Ontario, Canada",
    "CN Tower, Toronto, Canada", "Banff National Park, Alberta, Canada", "Chichen Itza, Yucatán, Mexico",
    "Teotihuacan, Mexico City, Mexico", "Tulum Ruins, Tulum, Mexico", "Iguazu Falls, Iguazu, Argentina",
    "Perito Moreno Glacier, Patagonia, Argentina", "Sugarloaf Mountain, Rio de Janeiro, Brazil", "Amazon Rainforest, Amazonas, Brazil",
    "Easter Island Moai, Easter Island, Chile", "Salar de Uyuni, Uyuni, Bolivia", "Table Mountain, Cape Town, South Africa",
    "Kruger National Park, Mpumalanga, South Africa", "Victoria Falls, Livingstone, Zambia", "Serengeti National Park, Serengeti, Tanzania",
    "Mount Kilimanjaro, Kilimanjaro, Tanzania", "Pyramids of Meroe, Meroe, Sudan", "Luxor Temple, Luxor, Egypt",
    "Valley of the Kings, Luxor, Egypt", "Abu Simbel Temples, Abu Simbel, Egypt", "Wadi Rum Desert, Wadi Rum, Jordan",
    "Dead Sea, Dead Sea, Jordan", "Western Wall, Jerusalem, Israel", "Dome of the Rock, Jerusalem, Israel",
    "Masada Fortress, Masada, Israel", "Persepolis, Shiraz, Iran", "Nasir al-Mulk Mosque, Shiraz, Iran",
    "Sheikh Lotfollah Mosque, Isfahan, Iran", "Bagan Temples, Bagan, Myanmar", "Shwedagon Pagoda, Yangon, Myanmar",
    "Ha Long Bay, Quang Ninh, Vietnam", "Angkor Thom, Siem Reap, Cambodia", "Borobudur Temple, Magelang, Indonesia",
    "Prambanan Temple, Yogyakarta, Indonesia", "Komodo Island, Komodo, Indonesia", "Petronas Towers, Kuala Lumpur, Malaysia",
    "Batu Caves, Selangor, Malaysia", "Marina Bay Sands, Singapore, Singapore", "Gardens by the Bay, Singapore, Singapore",
    "Great Buddha, Hong Kong, China", "Victoria Peak, Hong Kong, China", "Forbidden City, Beijing, China",
    "Summer Palace, Beijing, China", "Terracotta Army, Xi’an, China", "Zhangjiajie National Park, Zhangjiajie, China",
    "Potala Palace, Lhasa, Tibet", "Jokhang Temple, Lhasa, Tibet", "N Seoul Tower, Seoul, South Korea",
    "Gyeongbokgung Palace, Seoul, South Korea", "Jeju Island, Jeju, South Korea", "Taipei 101, Taipei, Taiwan",
    "Sun Moon Lake, Nantou, Taiwan", "Sigiriya Rock Fortress, Sigiriya, Sri Lanka", "Temple of the Tooth, Kandy, Sri Lanka",
    "Everest Base Camp, Khumbu, Nepal", "Annapurna Circuit, Annapurna, Nepal", "Tiger’s Nest Monastery, Paro, Bhutan",
    "Thimphu Buddha Dordenma, Thimphu, Bhutan", "Red Fort, Delhi, India", "Hawa Mahal, Jaipur, India",
    "Golden Temple, Amritsar, India", "Qutub Minar, Delhi, India", "Mehrangarh Fort, Jodhpur, India",
    "Phi Phi Islands, Krabi, Thailand", "Grand Palace, Bangkok, Thailand", "Wat Arun, Bangkok, Thailand",
    "Wat Phra Kaew, Bangkok, Thailand", "Ayutthaya Ruins, Ayutthaya, Thailand", "Uluru, Northern Territory, Australia",
    "Sydney Opera House, Sydney, Australia", "Sydney Harbour Bridge, Sydney, Australia", "Great Barrier Reef, Queensland, Australia",
    "Blue Mountains, New South Wales, Australia", "Hobbiton Movie Set, Matamata, New Zealand", "Milford Sound, Fiordland, New Zealand",
    "Sky Tower, Auckland, New Zealand", "Te Papa Museum, Wellington, New Zealand", "Cliffs of Moher, Clare, Ireland",
    "Blarney Castle, Cork, Ireland", "Giant’s Causeway, Antrim, United Kingdom", "Skellig Michael, Kerry, Ireland",
    "Meteora Monasteries, Kalambaka, Greece", "Delphi Ruins, Delphi, Greece", "Mykonos Windmills, Mykonos, Greece",
    "Dubrovnik Old Town, Dubrovnik, Croatia", "Plitvice Lakes, Plitvice, Croatia", "Lake Bled, Bled, Slovenia",
    "Predjama Castle, Postojna, Slovenia", "Bran Castle, Brasov, Romania", "Palace of Parliament, Bucharest, Romania",
    "Buda Castle, Budapest, Hungary", "Fisherman’s Bastion, Budapest, Hungary", "Auschwitz Memorial, Oswiecim, Poland",
    "Wieliczka Salt Mine, Krakow, Poland", "Wawel Castle, Krakow, Poland", "Vilnius Old Town, Vilnius, Lithuania",
    "Riga Old Town, Riga, Latvia", "Tallinn Old Town, Tallinn, Estonia", "Helsinki Cathedral, Helsinki, Finland",
    "Suomenlinna Fortress, Helsinki, Finland", "Tivoli Gardens, Copenhagen, Denmark", "Nyhavn Harbor, Copenhagen, Denmark",
    "Oslo Opera House, Oslo, Norway", "Geirangerfjord, Geiranger, Norway", "Preikestolen, Rogaland, Norway",
    "Icehotel, Jukkasjärvi, Sweden", "Vasa Museum, Stockholm, Sweden", "Gamla Stan, Stockholm, Sweden",
    "Blue Lagoon, Grindavik, Iceland", "Gullfoss Waterfall, Iceland", "Thingvellir National Park, Iceland",
    "Chamonix Mont Blanc, Chamonix, France", "Mont Blanc, Alps, France", "Matterhorn, Zermatt, Switzerland",
    "Jungfraujoch, Jungfrau Region, Switzerland", "Château de Chillon, Montreux, Switzerland", "Andorra la Vella Old Town, Andorra la Vella, Andorra",
    "Monaco Harbor, Monaco, Monaco", "Monte Carlo Casino, Monte Carlo, Monaco", "Carthage Ruins, Tunis, Tunisia",
    "Medina of Marrakech, Marrakech, Morocco", "Hassan II Mosque, Casablanca, Morocco", "Ait Benhaddou, Ouarzazate, Morocco",
    "Lalibela Churches, Lalibela, Ethiopia", "Simien Mountains, Amhara, Ethiopia", "Robben Island, Cape Town, South Africa",
    "Okavango Delta, Botswana, Botswana", "Skeleton Coast, Namibia, Namibia", "Petra Treasury, Petra, Jordan",
    "Dead Sea Scrolls Cave, Qumran, West Bank", "Mount Sinai, Sinai Peninsula, Egypt", "Roman Forum, Rome, Italy",
    "Vatican Museums, Vatican City, Vatican City", "Sistine Chapel, Vatican City, Vatican City", "Florence Cathedral, Florence, Italy",
    "Uffizi Gallery, Florence, Italy", "Ponte Vecchio, Florence, Italy", "Grand Canal, Venice, Italy",
    "St Mark’s Basilica, Venice, Italy", "Rialto Bridge, Venice, Italy", "Amalfi Coast, Amalfi, Italy",
    "Capri Island, Capri, Italy", "Mount Etna, Sicily, Italy", "Sacré-Cœur Basilica, Paris, France",
    "Dune of Pilat, Arcachon, France", "Strasbourg Cathedral, Strasbourg, France", "Carcassonne Citadel, Carcassonne, France",
    "Pont du Gard, Nîmes, France", "Chartres Cathedral, Chartres, France", "La Rambla, Barcelona, Spain",
    "Plaza Mayor, Madrid, Spain", "Prado Museum, Madrid, Spain", "Royal Palace of Madrid, Madrid, Spain",
    "Seville Cathedral, Seville, Spain", "Plaza de España, Seville, Spain", "Guggenheim Museum, Bilbao, Spain",
    "Santiago de Compostela Cathedral, Santiago, Spain", "Belém Tower, Lisbon, Portugal", "Jerónimos Monastery, Lisbon, Portugal",
    "Pena Palace, Sintra, Portugal", "Quinta da Regaleira, Sintra, Portugal", "Ribeira District, Porto, Portugal",
    "London Eye, London, United Kingdom", "Westminster Abbey, London, United Kingdom", "Lake District National Park, Cumbria, United Kingdom",
    "Tower of London, London, United Kingdom", "St Paul’s Cathedral, London, United Kingdom", "Miniatur Wunderland, Hamburg, Germany",
    "Heidelberg Castle, Heidelberg, Germany", "Sanssouci Palace, Potsdam, Germany", "Marienplatz, Munich, Germany",
    "Belvedere Palace, Vienna, Austria", "Salzburg Old Town, Salzburg, Austria", "Hohensalzburg Fortress, Salzburg, Austria",
    "Old Town Square, Prague, Czech Republic", "Astronomical Clock, Prague, Czech Republic", "Hungarian Parliament Building, Budapest, Hungary",
    "Chain Bridge, Budapest, Hungary", "Postojna Cave, Postojna, Slovenia", "Plitvice Lakes National Park, Plitvice, Croatia",
    "Diocletian’s Palace, Split, Croatia", "Peles Castle, Sinaia, Romania", "Malbork Castle, Malbork, Poland",
    "Kronborg Castle, Helsingør, Denmark", "Lofoten Islands, Lofoten, Norway", "Drottningholm Palace, Stockholm, Sweden",
    "Skogafoss Waterfall, Iceland", "Seljalandsfoss Waterfall, Iceland", "Lake Geneva, Geneva, Switzerland",
    "Meteora Viewpoints, Kalambaka, Greece", "Mount Olympus, Thessaly, Greece", "Lake Como, Como, Italy",
    "Dolomites Mountains, Dolomites, Italy", "Zermatt Village, Zermatt, Switzerland", "Aletsch Glacier, Valais, Switzerland",
    "Sognefjord, Sogn og Fjordane, Norway", "Hardangerfjord, Hardanger, Norway", "Reynisfjara Beach, Vik, Iceland",
    "Golden Circle, Iceland", "Zakopane Tatra Mountains, Zakopane, Poland", "Meteora Monastery Viewpoint, Kalambaka, Greece",
    "Sintra National Palace, Sintra, Portugal", "Pena Park, Sintra, Portugal", "Montjuïc Castle, Barcelona, Spain",
    "Camp Nou Stadium, Barcelona, Spain", "Retiro Park, Madrid, Spain", "Toledo Old Town, Toledo, Spain",
    "Segovia Aqueduct, Segovia, Spain", "Alcázar of Segovia, Segovia, Spain", "Ronda Bridge, Ronda, Spain",
    "Alcázar of Seville, Seville, Spain", "Costa Brava Coastline, Girona, Spain", "Ibiza Old Town, Ibiza, Spain",
    "Mallorca Cathedral, Palma, Spain", "Teide National Park, Tenerife, Spain", "Pico del Teide, Tenerife, Spain",
    "Canary Sand Dunes, Gran Canaria, Spain", "Madeira Cliffs, Madeira, Portugal", "Cabo da Roca, Sintra, Portugal",
    "Douro River Valley, Douro, Portugal", "Fátima Sanctuary, Fátima, Portugal", "Guimarães Castle, Guimarães, Portugal",
    "Aveiro Canals, Aveiro, Portugal", "Azores Sete Cidades Lake, Azores, Portugal", "Azores Lagoa do Fogo, Azores, Portugal",
    "Azores Furnas Lake, Azores, Portugal", "Azores Hot Springs, Azores, Portugal", "Brussels Grand Place, Brussels, Belgium",
    "Atomium, Brussels, Belgium", "Bruges Canals, Bruges, Belgium", "Belfry of Bruges, Bruges, Belgium",
    "Ghent Castle of the Counts, Ghent, Belgium", "Antwerp Cathedral, Antwerp, Belgium", "Luxembourg Old Town, Luxembourg City, Luxembourg",
    "Bock Casemates, Luxembourg City, Luxembourg", "Schengen Village, Schengen, Luxembourg", "Rotterdam Cube Houses, Rotterdam, Netherlands",
    "Kinderdijk Windmills, Kinderdijk, Netherlands", "Rijksmuseum, Amsterdam, Netherlands", "Anne Frank House, Amsterdam, Netherlands",
    "Van Gogh Museum, Amsterdam, Netherlands", "Keukenhof Gardens, Lisse, Netherlands", "Zaanse Schans Windmills, Zaanse Schans, Netherlands",
    "Giethoorn Village, Giethoorn, Netherlands", "Maastricht Old Town, Maastricht, Netherlands", "Utrecht Dom Tower, Utrecht, Netherlands",
    "Delft Old Town, Delft, Netherlands", "Alkmaar Cheese Market, Alkmaar, Netherlands", "Haarlem Old Town, Haarlem, Netherlands",
    "Marken Village, Marken, Netherlands", "Volendam Harbor, Volendam, Netherlands", "Texel Island, Texel, Netherlands",
    "Wadden Sea Islands, Wadden Sea, Netherlands", "Black Forest, Baden-Württemberg, Germany", "Zugspitze Mountain, Bavaria, Germany",
    "Königssee Lake, Bavaria, Germany", "Berchtesgaden National Park, Bavaria, Germany", "Rothenburg ob der Tauber Old Town, Rothenburg, Germany",
    "Wartburg Castle, Eisenach, Germany", "Bamberg Old Town, Bamberg, Germany", "Blue Mosque (Sultanahmet Camii), Istanbul, Türkiye",
    "Topkapi Palace, Istanbul, Türkiye", "Basilica Cistern, Istanbul, Türkiye", "Grand Bazaar, Istanbul, Türkiye",
    "Dolmabahce Palace, Istanbul, Türkiye", "Galata Tower, Istanbul, Türkiye", "Istiklal Street, Istanbul, Türkiye",
    "Bosphorus Bridge, Istanbul, Türkiye", "Ortakoy Mosque, Istanbul, Türkiye", "Maiden’s Tower, Istanbul, Türkiye",
    "Rumeli Fortress, Istanbul, Türkiye", "Balat Historic District, Istanbul, Türkiye", "Princes Islands, Istanbul, Türkiye",
    "Miniaturk Park, Istanbul, Türkiye", "Pierre Loti Hill, Istanbul, Türkiye", "Beylerbeyi Palace, Istanbul, Türkiye",
    "Yildiz Park, Istanbul, Türkiye", "Suleymaniye Mosque, Istanbul, Türkiye", "Chora Church, Istanbul, Türkiye",
    "Ephesus Ancient City, Izmir, Türkiye", "House of Virgin Mary, Izmir, Türkiye", "Sirince Village, Izmir, Türkiye",
    "Pergamon Ancient City, Bergama, Izmir, Türkiye", "Asclepion, Bergama, Izmir, Türkiye", "Kadifekale, Izmir, Türkiye",
    "Kordon Promenade, Izmir, Türkiye", "Cesme Marina, Izmir, Türkiye", "Alacati Windmills, Izmir, Türkiye",
    "Alacati Streets, Izmir, Türkiye", "Ilica Beach, Cesme, Izmir, Türkiye", "Foça Old Town, Izmir, Türkiye",
    "Karaburun Coast, Izmir, Türkiye", "Sığacık Village, Seferihisar, Izmir, Türkiye", "Teos Ancient City, Izmir, Türkiye",
    "Goreme Open Air Museum, Nevsehir, Türkiye", "Uchisar Castle, Nevsehir, Türkiye", "Derinkuyu Underground City, Nevsehir, Türkiye",
    "Kaymakli Underground City, Nevsehir, Türkiye", "Ihlara Valley, Aksaray, Türkiye", "Selime Monastery, Aksaray, Türkiye",
    "Hierapolis Ancient City, Denizli, Türkiye", "Laodicea Ancient City, Denizli, Türkiye", "Aspendos Theatre, Antalya, Türkiye",
    "Perge Ancient City, Antalya, Türkiye", "Side Ancient City, Antalya, Türkiye", "Manavgat Waterfall, Antalya, Türkiye",
    "Duden Waterfalls, Antalya, Türkiye", "Olympos Ancient City, Antalya, Türkiye", "Cirali Beach, Antalya, Türkiye",
    "Yanartas (Chimera Flames), Antalya, Türkiye", "Phaselis Ancient City, Antalya, Türkiye", "Konyaalti Beach, Antalya, Türkiye",
    "Lara Beach, Antalya, Türkiye", "Kaleici Old Town, Antalya, Türkiye", "Termessos Ancient City, Antalya, Türkiye",
    "Bodrum Castle, Mugla, Türkiye", "Mausoleum at Halicarnassus, Bodrum, Türkiye", "Bodrum Marina, Mugla, Türkiye",
    "Fethiye Oludeniz Lagoon, Mugla, Türkiye", "Butterfly Valley, Fethiye, Mugla, Türkiye", "Saklikent Canyon, Mugla, Türkiye",
    "Kayakoy Ghost Village, Mugla, Türkiye", "Dalyan River, Mugla, Türkiye", "Iztuzu Beach, Mugla, Türkiye",
    "Marmaris Marina, Mugla, Türkiye", "Datca Peninsula, Mugla, Türkiye", "Knidos Ancient City, Mugla, Türkiye",
    "Nemrut Statues, Adiyaman, Türkiye", "Sumela Monastery, Trabzon, Türkiye", "Uzungol Lake, Trabzon, Türkiye",
    "Hagia Sophia Trabzon, Trabzon, Türkiye", "Ayder Plateau, Rize, Türkiye", "Firtina Valley, Rize, Türkiye",
    "Safranbolu Old Town, Karabuk, Türkiye", "Tokatli Canyon, Safranbolu, Türkiye", "Amasra Harbor, Bartin, Türkiye",
    "Abant Lake, Bolu, Türkiye", "Yedigoller National Park, Bolu, Türkiye", "Uludag Mountain, Bursa, Türkiye",
    "Bursa Grand Mosque, Bursa, Türkiye", "Cumalikizik Village, Bursa, Türkiye", "Troy Ancient City, Canakkale, Türkiye",
    "Gallipoli Peninsula, Canakkale, Türkiye", "Assos Ancient City, Canakkale, Türkiye", "Mount Ararat, Agri, Türkiye",
    "Ishak Pasha Palace, Agri, Türkiye", "Ani Ruins, Kars, Türkiye", "Lake Cildir, Kars, Türkiye",
    "Lake Van, Van, Türkiye", "Akdamar Island Church, Van, Türkiye", "Hasankeyf Ruins, Batman, Türkiye",
    "Mardin Old Town, Mardin, Türkiye", "Dara Ancient City, Mardin, Türkiye", "Sanliurfa Balikli Gol, Sanliurfa, Türkiye",
    "Gobekli Tepe, Sanliurfa, Türkiye", "Harran Houses, Sanliurfa, Türkiye"
];
